### ISSUE TITLE
Remove releseases 4.1.6 and 4.1.5

### ISSUE THREAD

**Issue by bidi47** [dotkernel/dot-annotated-services#33]
versions 4.1.6 and 4.1.5 require doctrine/annotations: ^2.0.1 which causes bugs

**Comment by arhimede** [comment]
again, why should be removed those 2 ?

**Comment by bidi47** [comment]
@arhimede both versions are in packagist again
do we want to keep them after all?

**Comment by arhimede** [comment]
yeah, i forgot to delete the tags too 

Now are gone for good
