### ISSUE TITLE
[RFC]: Revert package to use annotations instead of attributes

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/dot-annotated-services#52]
## RFC

Since we have `dot-dependency-injection` which is attribute-based, shouldn't we revert this package to the last version it was using annotations, `4.x`?

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | ~~x.y.0~~  |
| BC Break?           | Yes |

### Goal

Package name should reflect its purpose.
If it's called `dot-annotated-services`, it should use **annotations**, like it did before.

### Considerations

First, we must check live projects that use the latest version of `dot-annotated-services` (with attributes) and switch them to `dot-dependency-injection`.

### Proposal(s)

Once we ensure that live projects have either switched to attributes using `dot-dependency-injection` or have not upgraded to version 5 of this package, we can delete `5.x` and go back to version `4.x` OR create `5.x` from `4.x`.
Also, documentation will need adjustments as it too is attribute-based.

**Comment by arhimede** [comment]
- 5.x branch will be marked as  "security"
- 4.x   branch will be marked as "active "
- current version will be 4.x branch ( main and default branch )
-  modifications from 5.x --> 4.x  except the attributes
- in 4.x increase  doctrine to 2.20 
- documentation fixed to show 4.x as default , and v5 as old ....
