### ISSUE TITLE
dot-annotated-services - tags, php version, packets

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-annotated-services#7]
update tags and packets 
including php ~7.4.0 || ~8.0.0 || ~8.1.0

note: waiting on doctrine/annotations and doctrine/cache which still require only php: ^7.1 || ^8.0 even at the most recent versions

**Comment by bidi47** [comment]
merged update in 
https://github.com/dotkernel/dot-annotated-services/pull/8

note: doctrine/annotations 1.13 and doctrine/cache 2.1 still support only up to php 8.0

**Comment by arhimede** [comment]
@bidi47  
dotrine/annotiation work with any PHP version : 
   "php": "^7.1 || ^8.0",  in composer.json , line 16

**Comment by arhimede** [comment]
@bidi47 
the same for doctrine/cache
https://github.com/doctrine/cache/blob/2.1.x/composer.json

So we can release this one.

**Comment by arhimede** [comment]
fixed in #8
