### ISSUE TITLE
Conflict with doctrine/cache versions

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-annotated-services#9]
https://github.com/Roave/psr-container-doctrine is set to doctrine/cache 1

please check if we can downgrade this package to 1

**Comment by bidi47** [comment]
updated in https://github.com/dotkernel/dot-annotated-services/pull/11

**Comment by bidi47** [comment]
revisited in https://github.com/dotkernel/dot-annotated-services/pull/28/files
